import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import ToasterProvider from '@/components/providers/toaster-provider'
import ConfettiProvider from '@/components/providers/ConfettiProvider'
import { AuthProvider } from './Providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    // <ClerkProvider>
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <ConfettiProvider/>
          <ToasterProvider/>
          {children}
        
        </body>
      </html>
      </AuthProvider>
    // </ClerkProvider>
  )
}
